#use the "- " prefix to force an array rather than an unordered hash

-
  :label: Identifying Data
  :controller: IdentifyingDatasController
  :show:  :abstract_identifying_data_path
-
  :label: Bone Marrow
  :controller: BoneMarrowsController
  :show:  :abstract_bone_marrow_path
-
  :label: Flow Cytometry
  :controller: FlowCytometriesController
  :show:  :abstract_flow_cytometry_path
-
  :label: TDT
  :controller: TdtsController
  :show:  :abstract_tdt_path
-
  :label: Histocompatibility
  :controller: HistocompatibilitiesController
  :show:  :abstract_histocompatibility_path
-
  :label: Cytogenetics
  :controller: CytogeneticsController
  :show:  :abstract_cytogenetic_path
-
  :label: CBC
  :controller: CbcsController
  :show:  :abstract_cbc_path
-
  :label: Cerebrospinal Fluid
  :controller: CerebrospinalFluidsController
  :show:  :abstract_cerebrospinal_fluid_path
-
  :label: Chest Imaging
  :controller: ChestImagingsController
  :show:  :abstract_chest_imaging_path
-
  :label: "H &amp; P / Discharge"
  :controller: DischargesController
  :show:  :abstract_discharge_path
-
  :label: Clinical Chemo Protocol
  :controller: ClinicalChemoProtocolsController
  :show:  :abstract_clinical_chemo_protocol_path
-
  :label: Response to Therapy
  :controller: TherapyResponsesController
  :show:  :abstract_therapy_response_path
-
  :label: Diagnosis
  :controller: DiagnosesController
  :show:  :abstract_diagnosis_path
-
  :label: Checklist
  :controller: ChecklistsController
  :show:  :abstract_checklist_path
-
  :label: Name
  :controller: NamesController
  :show:  :abstract_name_path
